name: default

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        # Set working directory to /test-monorepo folder for all 'run' commands.
        # Commands using 'uses' will need options passed in.
        working-directory: ./test-monorepo

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_USER_PAT }}

      - name: configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - run: yarn install

      - run: npx nx run-many --target=semantic-release --parallel=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
